#!/usr/bin/env python3
"""
Parse Texas GOP County Chairs data from the leadership directory page
"""

import json
import re
from datetime import datetime

# Raw Texas county chairs data extracted from the website
# Format: County Name: Chair Name (email available via "Send Email")
TEXAS_COUNTY_CHAIRS = {
    'Anderson': 'Dan Wilford',
    'Andrews': 'Beth Culbertson',
    'Angelina': 'Michael McCracken',
    'Aransas': 'Katy Jackson',
    'Archer': 'Leslie Hash',
    'Armstrong': 'Ray Minkley',
    'Atascosa': 'Robert Duncan',
    'Austin': 'Charles "Chuck" Beers',
    'Bailey': 'Carroll Precure',
    'Bandera': 'Denise Gober',
    'Bastrop': 'Justin Bezner',
    'Baylor': 'John R. Zielasko',
    'Bee': 'Patty Johnson',
    'Bell': 'Addie Baird',
    'Bexar': 'Kris Coons',
    'Blanco': 'Carlette Lewis',
    'Borden': 'Diedra Parks',
    'Bosque': 'Hank Dawson',
    'Bowie': 'Gary Singleton',
    'Brazoria': 'Shayne Green',
    'Brazos': 'Russell Ford',
    'Brewster': 'Monica McBride',
    'Briscoe': 'Timothy Kent',
    'Brooks': 'Jessica Lopez',
    'Brown': 'Robert Porter',
    'Burleson': 'Karen Bolt',
    'Burnet': 'Tammy Hullum',
    'Caldwell': 'Luz Riley',
    'Calhoun': 'Russell Cain',
    'Callahan': 'Kathleen Tippy',
    'Cameron': 'Deborah Bell',
    'Camp': 'Cynthia Wilson',
    'Carson': 'Charles Kincade',
    'Cass': 'Carolyn Lance',
    'Castro': 'Sheryl Brown',
    'Chambers': 'David Redd',
    'Cherokee': 'Janet Stanovich',
    'Childress': 'James Driver',
    'Clay': 'Sharon Adkins',
    'Cochran': 'John Schmidt',
    'Coke': 'Deborah Bailey',
    'Coleman': 'Bridget Wakefield',
    'Collin': 'Byron Henry',
    'Collingsworth': 'Vacant',
    'Colorado': 'Tom Kelley',
    'Comal': 'Anita Valdez',
    'Comanche': 'Linda Kinsey',
    'Concho': 'Cathy Ator',
    'Cooke': 'Chris McNamara',
    'Coryell': 'Norman Mitchell',
    'Cottle': 'Patrick Rhodes',
    'Crane': 'Tom Currie',
    'Crockett': 'Vacant',
    'Crosby': 'Melanie Snodgrass',
    'Culberson': 'Vacant',
    'Dallam': 'Selene Schumacher',
    'Dallas': 'Allen West',
    'Dawson': 'Beverly Beaty',
    'Deaf Smith': 'Vacant',
    'Delta': 'Vacant',
    'Denton': 'Melinda Preston',
    'DeWitt': 'Jeanne Seidel',
    'Dickens': 'Jody Duggan',
    'Dimmit': 'Paula Campos Seydel',
    'Donley': 'Bill Word',
    'Duval': 'Mary Wilson',
    'Eastland': 'Robin Hayes',
    'Ector': 'Donna Kelm',
    'Edwards': 'Kathy Walker',
    'El Paso': 'Michael Aboud',
    'Ellis': 'Randy Bellomy',
    'Erath': 'Dave Washam',
    'Falls': 'Elizabeth Nelson',
    'Fannin': 'Darren York',
    'Fayette': 'Michael P. Schlabach',
    'Fisher': 'Johnnie Howell',
    'Floyd': 'Kerry D. Pratt',
    'Foard': 'Jaime Durham',
    'Fort Bend': 'Bobby Eberle',
    'Franklin': 'Charlie Wilson',
    'Freestone': 'Keith Turchi',
    'Frio': 'Nathan Rodriguez',
    'Gaines': 'Stacie Via',
    'Galveston': 'Patrick McGinnis',
    'Garza': 'Vacant',
    'Gillespie': 'Bruce Campbell',
    'Glasscock': 'Mandie McIlroy',
    'Goliad': 'Dana Dobbs',
    'Gonzales': 'Liz Hernandez',
    'Gray': 'Ann Franklin',
    'Grayson': 'Brent Lawson',
    'Gregg': 'William McWhorter',
    'Grimes': 'Alec Pointer',
    'Guadalupe': 'Karen Hale',
    'Hale': 'Wayne Post',
    'Hall': 'Kacee McGraw',
    'Hamilton': 'Joelle Jocis',
    'Hansford': 'Gyene Spivey',
    'Hardeman': 'Wesley Smith',
    'Hardin': 'Donald Burnett',
    'Harris': 'Cindy Siegel',
    'Harrison': 'Mary Napps',
    'Hartley': 'Mike Thompson',
    'Haskell': 'Paul Leonard',
    'Hays': 'Michelle Lopez',
    'Hemphill': 'Kyle Barnett',
    'Henderson': 'Krista Stutts',
    'Hidalgo': 'Robert Cantu',
    'Hill': 'Will Orr',
    'Hockley': 'Pat Cowan',
    'Hood': 'Gregory Harrell',
    'Hopkins': 'Donnie Wisenbaker',
    'Houston': 'Joni Clonts',
    'Howard': 'Teresa Griffin',
    'Hudspeth': 'Avi Nash',
    'Hunt': 'David Hale',
    'Hutchinson': 'Mary Kay Phelan',
    'Irion': 'Michelle Rushing',
    'Jack': 'John Berry',
    'Jackson': 'David Webel',
    'Jasper': 'Johnny Gravis',
    'Jeff Davis': 'Matt Blackman',
    'Jefferson': 'Joe Evans',
    'Jim Hogg': 'Phillip Worley',
    'Jim Wells': 'Charlie Ragland',
    'Johnson': 'Robin Wilson',
    'Jones': 'David Andrews',
    'Karnes': 'Vacant',
    'Kaufman': 'Jody Deller',
    'Kendall': 'Jennifer Barreras-Rawls',
    'Kenedy': 'Jill Brown',
    'Kent': 'Kathy Owen',
    'Kerr': 'Helen Herd',
    'Kimble': 'Kaitlyn Hicks',
    'King': 'Pat Bradbury',
    'Kinney': 'Stephen Foxx',
    'Kleberg': 'Randi Michelle Bearden',
    'Knox': 'Vacant',
    'La Salle': 'Susan Rubio',
    'Lamar': 'Scott Hommell',
    'Lamb': 'James Stephen Busby',
    'Lampasas': 'Wendy Daugherty',
    'Lavaca': 'Lorena Kanak',
    'Lee': 'Shann Turner',
    'Leon': 'Carol Milder',
    'Liberty': 'Wes Thomas',
    'Limestone': 'Lance Phillips',
    'Lipscomb': 'Diana Hoover',
    'Live Oak': 'Lori Pridgen',
    'Llano': 'Jessica McRee-Grabert',
    'Loving': 'Alan Haley',
    'Lubbock': 'Jon David Bruegel',
    'Lynn': 'John B. Baker',
    'Madison': 'Brett Bousman',
    'Marion': 'Hunter Bonner',
    'Martin': 'John Myrick',
    'Mason': 'Wanda Rueffer',
    'Matagorda': 'Robert Shirley',
    'Maverick': 'Sandy Sassano',
    'McCulloch': 'Dixie Pitcox',
    'McLennan': 'Christopher DeCluitt',
    'McMullen': 'Jeb Hogan',
    'Medina': 'Chris Schuchart',
    'Menard': 'George Corbin',
    'Midland': 'James Beauchamp',
    'Milam': 'Rebecca Luckey',
    'Mills': 'Buddy Williams',
    'Mitchell': 'Liz Oakley',
    'Montague': 'Melody Gillespie',
    'Montgomery': 'Gwen Withrow',
    'Moore': 'Sue Sims',
    'Morris': 'Belinda McLaughlin',
    'Motley': 'Gary Stone',
    'Nacogdoches': 'Nicole Tarpley',
    'Navarro': 'Steve Jessup',
    'Newton': 'Pamela Bourdeau',
    'Nolan': 'Larry May',
    'Nueces': 'Carmen Calderone',
    'Ochiltree': 'Sandra Sears',
    'Oldham': 'Cheri Webb',
    'Orange': 'Cheryl Warren',
    'Palo Pinto': 'Barbara Upham',
    'Panola': 'Mark Williams',
    'Parker': 'Brady Gray',
    'Parmer': 'Bill White',
    'Pecos': 'Darlene Stegall',
    'Polk': 'Paul Laverty',
    'Potter': 'Dan Rogers',
    'Presidio': 'Dan Dunlap',
    'Rains': 'Lisa Kruger',
    'Randall': 'Kelly Giles',
    'Reagan': 'Melissa Holt',
    'Real': 'Jack DuBose',
    'Red River': 'Cebron OBier',
    'Reeves': 'Polly Nance',
    'Refugio': 'Sylvia Barrera-Wiginton',
    'Roberts': 'Jennifer Wheeler',
    'Robertson': 'Mark Burow',
    'Rockwall': 'Sharon Henson',
    'Runnels': 'Elizabeth OConnor',
    'Rusk': 'Rachel Hale',
    'Sabine': 'Ceci Matthews',
    'San Augustine': 'Arthur Bedford',
    'San Jacinto': 'Dwayne Wright',
    'San Patricio': 'Rex Warner',
    'San Saba': 'Jeffrey Carlson',
    'Schleicher': 'Jeri Johnson Willoughby',
    'Scurry': 'Deborah Boyd',
    'Shackelford': 'Rodney Casey',
    'Shelby': 'Leigh Porterfield',
    'Sherman': 'Susie Spurlock',
    'Smith': 'David Stein',
    'Somervell': 'Tonya Webster-Logsdon',
    'Starr': 'Toni Trevino',
    'Stephens': 'Scott Harris',
    'Sterling': 'Judie Williams',
    'Stonewall': 'Butch Nuding',
    'Sutton': 'Ben Pool',
    'Swisher': 'Vacant',
    'Tarrant': 'Tim Davis',
    'Taylor': 'Ryan Goodwin',
    'Terrell': 'Alex Nash-Ford',
    'Terry': 'Eric Horton',
    'Throckmorton': 'Vacant',
    'Titus': 'Sue Evenwell',
    'Tom Green': 'Bruce Burkett',
    'Travis': 'Jennifer Fleck',
    'Trinity': 'Scott Womack',
    'Tyler': 'Robert Poynter',
    'Upshur': 'Carl Byers',
    'Upton': 'Tammie Smith',
    'Uvalde': 'Charles Downing',
    'Val Verde': 'Sharon Petitt',
    'Van Zandt': 'Lance Lenz',
    'Victoria': 'Bill Pozzi',
    'Walker': 'Linda McKenzie',
    'Waller': 'Cyndi Lawrence',
    'Ward': 'Dean Chadic',
    'Washington': 'Sandra Kindt',
    'Webb': 'Jose Salazar',
    'Wharton': 'Domingo Montalvo Jr',
    'Wheeler': 'Terralyn Miles',
    'Wichita': 'Julie Wilson',
    'Wilbarger': 'Meredith Wright',
    'Willacy': 'Maria McKee',
    'Williamson': 'Michelle Evans',
    'Wilson': 'Joyce Miller',
    'Winkler': 'Shawna Doran',
    'Wise': 'Dan Jackson',
    'Wood': 'Kathy Wakeman',
    'Yoakum': 'Kyle Stephens',
    'Young': 'Lane Burgess',
    'Zapata': 'Jennifer Longoria-Thatcher',
    'Zavala': 'Richard Diaz',
}

def clean_id(text):
    clean = re.sub(r'[,./:\s\'-]+', '-', text.lower())
    return clean.strip('-')

def generate_texas_data():
    """Generate Texas county chair data in the standard format"""
    chairs = []

    for county, chair_name in TEXAS_COUNTY_CHAIRS.items():
        chairs.append({
            'id': f'TX-{clean_id(county)}',
            'state': 'Texas',
            'stateCode': 'TX',
            'county': f'{county} County',
            'chairName': chair_name,
            'email': None,  # Emails are available via contact forms on the website
            'phone': None,
            'electionDate': None,
            'source': 'https://texasgop.org/leadership-directory/',
            'lastVerified': datetime.now().strftime('%Y-%m-%d'),
            'notes': None
        })

    return chairs

if __name__ == "__main__":
    texas_chairs = generate_texas_data()

    print(f"Generated {len(texas_chairs)} Texas county chair records")

    # Save to JSON
    output_file = '/Users/robertmalka/Desktop/gop-county-chairs/scraper/texas_chairs.json'
    with open(output_file, 'w') as f:
        json.dump(texas_chairs, f, indent=2)

    print(f"Saved to {output_file}")

    # Show sample
    print("\nSample records:")
    for chair in texas_chairs[:5]:
        print(f"  {chair['county']}: {chair['chairName']}")
